#!/bin/sh
set -e
package_name=smplayer-enqueue-hide
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/smplayer_enqueue.desktop"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/smplayer_enqueue.desktop"
;;
esac
exit 0
